import { bigint, boolean, index, integer, jsonb, pgEnum, pgTable, text, timestamp, uniqueIndex, uuid } from 'drizzle-orm/pg-core'

export const role = pgEnum('user_role', ['supporter', 'ngo', 'corporate', 'admin'])
export const campaignStatus = pgEnum('campaign_status', ['draft', 'pending_review', 'changes_requested', 'rejected', 'approved', 'active', 'paused', 'completed', 'cancelled'])
export const verificationStatus = pgEnum('verification_status', ['draft', 'submitted', 'changes_requested', 'verified', 'rejected', 'expired'])

const timestamps = { createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(), updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow().notNull() }
export const users = pgTable('users', { id: uuid('id').defaultRandom().primaryKey(), name: text('name').notNull(), email: text('email').notNull(), emailVerified: boolean('email_verified').default(false).notNull(), image: text('image'), role: role('role').default('supporter').notNull(), ...timestamps }, (t) => [uniqueIndex('users_email_unique').on(t.email)])
export const sessions = pgTable('sessions', { id: text('id').primaryKey(), userId: uuid('user_id').references(() => users.id, { onDelete: 'cascade' }).notNull(), token: text('token').notNull(), expiresAt: timestamp('expires_at', { withTimezone: true }).notNull(), ipAddress: text('ip_address'), userAgent: text('user_agent'), ...timestamps }, (t) => [uniqueIndex('sessions_token_unique').on(t.token), index('sessions_user_idx').on(t.userId)])
export const accounts = pgTable('accounts', { id: text('id').primaryKey(), userId: uuid('user_id').references(() => users.id, { onDelete: 'cascade' }).notNull(), accountId: text('account_id').notNull(), providerId: text('provider_id').notNull(), password: text('password'), accessToken: text('access_token'), refreshToken: text('refresh_token'), accessTokenExpiresAt: timestamp('access_token_expires_at', { withTimezone: true }), refreshTokenExpiresAt: timestamp('refresh_token_expires_at', { withTimezone: true }), scope: text('scope'), idToken: text('id_token'), ...timestamps })
export const verifications = pgTable('verifications', { id: text('id').primaryKey(), identifier: text('identifier').notNull(), value: text('value').notNull(), expiresAt: timestamp('expires_at', { withTimezone: true }).notNull(), ...timestamps })
export const ngoProfiles = pgTable('ngo_profiles', { id: uuid('id').defaultRandom().primaryKey(), ownerId: uuid('owner_id').references(() => users.id).notNull(), displayName: text('display_name').notNull(), slug: text('slug').notNull(), description: text('description'), city: text('city'), state: text('state'), categories: text('categories').array().default([]).notNull(), verificationStatus: verificationStatus('verification_status').default('draft').notNull(), isDiscoverable: boolean('is_discoverable').default(false).notNull(), is80gEligible: boolean('is_80g_eligible').default(false).notNull(), ...timestamps }, (t) => [uniqueIndex('ngo_profiles_slug_unique').on(t.slug)])
export const payoutAccounts = pgTable('payout_accounts', { id: uuid('id').defaultRandom().primaryKey(), ownerId: uuid('owner_id').references(() => users.id).notNull(), provider: text('provider').notNull(), gatewayAccountId: text('gateway_account_id'), status: text('status').default('pending').notNull(), beneficiary: jsonb('beneficiary'), ...timestamps })
export const campaigns = pgTable('campaigns', { id: uuid('id').defaultRandom().primaryKey(), creatorId: uuid('creator_id').references(() => users.id).notNull(), ngoId: uuid('ngo_id').references(() => ngoProfiles.id), payoutAccountId: uuid('payout_account_id').references(() => payoutAccounts.id), title: text('title').notNull(), story: text('story').notNull(), targetPaise: bigint('target_paise', { mode: 'number' }).notNull(), status: campaignStatus('status').default('draft').notNull(), ...timestamps }, (t) => [index('campaigns_status_idx').on(t.status)])
export const donations = pgTable('donations', { id: uuid('id').defaultRandom().primaryKey(), donorId: uuid('donor_id').references(() => users.id).notNull(), campaignId: uuid('campaign_id').references(() => campaigns.id).notNull(), amountPaise: bigint('amount_paise', { mode: 'number' }).notNull(), gatewayOrderId: text('gateway_order_id').notNull(), gatewayPaymentId: text('gateway_payment_id').notNull(), status: text('status').notNull(), capturedAt: timestamp('captured_at', { withTimezone: true }).notNull(), ...timestamps }, (t) => [uniqueIndex('donations_order_unique').on(t.gatewayOrderId), uniqueIndex('donations_payment_unique').on(t.gatewayPaymentId)])
export const paymentEvents = pgTable('payment_events', { id: uuid('id').defaultRandom().primaryKey(), gatewayEventId: text('gateway_event_id').notNull(), eventType: text('event_type').notNull(), payload: jsonb('payload').notNull(), processedAt: timestamp('processed_at', { withTimezone: true }), createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull() }, (t) => [uniqueIndex('payment_events_gateway_unique').on(t.gatewayEventId)])
export const volunteerApplications = pgTable('volunteer_applications', { id: uuid('id').defaultRandom().primaryKey(), userId: uuid('user_id').references(() => users.id).notNull(), ngoId: uuid('ngo_id').references(() => ngoProfiles.id).notNull(), status: text('status').default('submitted').notNull(), ...timestamps })
export const posts = pgTable('posts', { id: uuid('id').defaultRandom().primaryKey(), authorId: uuid('author_id').references(() => users.id).notNull(), body: text('body').notNull(), approvedAt: timestamp('approved_at', { withTimezone: true }), hiddenAt: timestamp('hidden_at', { withTimezone: true }), ...timestamps })
export const auditLogs = pgTable('audit_logs', { id: uuid('id').defaultRandom().primaryKey(), actorId: uuid('actor_id').references(() => users.id), action: text('action').notNull(), entityType: text('entity_type').notNull(), entityId: text('entity_id'), metadata: jsonb('metadata'), createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull() })
export const reviews = pgTable('reviews', { id: uuid('id').defaultRandom().primaryKey(), userId: uuid('user_id').references(() => users.id).notNull(), ngoId: uuid('ngo_id').references(() => ngoProfiles.id).notNull(), rating: integer('rating').notNull(), body: text('body'), hiddenAt: timestamp('hidden_at', { withTimezone: true }), createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull() }, (t) => [uniqueIndex('reviews_user_ngo_unique').on(t.userId, t.ngoId)])
