ALTER TABLE campaigns ADD COLUMN short_description TEXT;
ALTER TABLE campaigns ADD COLUMN category TEXT NOT NULL DEFAULT 'general';
ALTER TABLE campaigns ADD COLUMN image_url TEXT;
ALTER TABLE campaigns ADD COLUMN deadline TIMESTAMPTZ;
ALTER TABLE campaigns ADD COLUMN beneficiary JSONB;
ALTER TABLE campaigns ADD COLUMN evidence JSONB NOT NULL DEFAULT '[]';
ALTER TABLE campaigns ADD COLUMN approved_at TIMESTAMPTZ;
CREATE INDEX campaigns_discovery_idx ON campaigns(status, category, created_at DESC);
CREATE INDEX ngo_profiles_discovery_idx ON ngo_profiles(is_discoverable, verification_status, state, city);

CREATE TABLE campaign_updates (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), campaign_id UUID NOT NULL REFERENCES campaigns(id) ON DELETE CASCADE, author_id UUID NOT NULL REFERENCES users(id), title TEXT NOT NULL, body TEXT NOT NULL, published_at TIMESTAMPTZ, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE follows (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE, ngo_id UUID NOT NULL REFERENCES ngo_profiles(id) ON DELETE CASCADE, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), UNIQUE(user_id, ngo_id));
CREATE TABLE payment_orders (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), user_id UUID NOT NULL REFERENCES users(id), campaign_id UUID NOT NULL REFERENCES campaigns(id), amount_paise BIGINT NOT NULL CHECK(amount_paise > 0), gateway_order_id TEXT NOT NULL UNIQUE, status TEXT NOT NULL DEFAULT 'created', expires_at TIMESTAMPTZ NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE subscriptions (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), user_id UUID NOT NULL REFERENCES users(id), campaign_id UUID NOT NULL REFERENCES campaigns(id), amount_paise BIGINT NOT NULL CHECK(amount_paise > 0), cadence TEXT NOT NULL CHECK(cadence IN ('monthly','quarterly','yearly')), gateway_plan_id TEXT NOT NULL, gateway_subscription_id TEXT NOT NULL UNIQUE, status TEXT NOT NULL DEFAULT 'created', current_period_end TIMESTAMPTZ, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE refunds (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), donation_id UUID NOT NULL REFERENCES donations(id), requester_id UUID NOT NULL REFERENCES users(id), reason TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'requested', gateway_refund_id TEXT UNIQUE, reviewed_by UUID REFERENCES users(id), reviewed_at TIMESTAMPTZ, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE receipts (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), donation_id UUID NOT NULL UNIQUE REFERENCES donations(id), receipt_number TEXT NOT NULL UNIQUE, financial_year TEXT NOT NULL, issued_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE tax_certificates (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), donation_id UUID NOT NULL UNIQUE REFERENCES donations(id), ngo_id UUID NOT NULL REFERENCES ngo_profiles(id), financial_year TEXT NOT NULL, storage_key TEXT NOT NULL UNIQUE, uploaded_by UUID NOT NULL REFERENCES users(id), issued_at DATE NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE payout_transfers (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), payout_account_id UUID NOT NULL REFERENCES payout_accounts(id), donation_id UUID REFERENCES donations(id), amount_paise BIGINT NOT NULL CHECK(amount_paise > 0), gateway_transfer_id TEXT UNIQUE, status TEXT NOT NULL DEFAULT 'pending', failure_reason TEXT, reversed_at TIMESTAMPTZ, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
