'use server'
import { and, eq, sql } from 'drizzle-orm'
import { revalidatePath } from 'next/cache'
import { z } from 'zod'
import { requireSession } from '@/lib/auth/session'
import { db } from '@/lib/db'
import { ngoProfiles, notifications, volunteerApplications, volunteerCertificates, volunteerHours, volunteerOpportunities } from '@/lib/db/schema'
async function ownedNgo(){const session=await requireSession();const[ngo]=await db.select().from(ngoProfiles).where(eq(ngoProfiles.ownerId,session.user.id)).limit(1);if(!ngo)throw new Error('NGO profile required.');return{session,ngo}}
const csv=(v:FormDataEntryValue|null)=>String(v??'').split(',').map(x=>x.trim().toLowerCase()).filter(Boolean)
export async function createOpportunityAction(form:FormData){const{ngo}=await ownedNgo();if(ngo.verificationStatus!=='verified')throw new Error('NGO verification is required.');const data=z.object({title:z.string().trim().min(8).max(160),description:z.string().trim().min(40).max(5000),city:z.string().trim().max(100),state:z.string().trim().max(100),capacity:z.coerce.number().int().min(1).max(10000)}).parse(Object.fromEntries(form));await db.insert(volunteerOpportunities).values({ngoId:ngo.id,...data,skills:csv(form.get('skills')),availability:csv(form.get('availability')),remote:form.get('remote')==='on',status:'published'});revalidatePath('/ngo/dashboard/volunteers')}
export async function decideApplicationAction(form:FormData){const{session,ngo}=await ownedNgo();const data=z.object({applicationId:z.string().uuid(),status:z.enum(['shortlisted','accepted','rejected'])}).parse(Object.fromEntries(form));const[updated]=await db.update(volunteerApplications).set({status:data.status,updatedAt:new Date()}).where(and(eq(volunteerApplications.id,data.applicationId),eq(volunteerApplications.ngoId,ngo.id))).returning({userId:volunteerApplications.userId});if(updated)await db.insert(notifications).values({userId:updated.userId,type:'volunteer_application',title:'Volunteer application updated',body:`Your application is now ${data.status}.`,href:'/dashboard/volunteering'});await db.insert(notifications).values({userId:session.user.id,type:'audit',title:'Application decision recorded',body:`Application marked ${data.status}.`});revalidatePath('/ngo/dashboard/volunteers')}
export async function approveHoursAction(form:FormData){const{session,ngo}=await ownedNgo();const data=z.object({hoursId:z.string().uuid(),status:z.enum(['approved','rejected'])}).parse(Object.fromEntries(form));const[record]=await db.select({id:volunteerHours.id,minutes:volunteerHours.minutes,userId:volunteerApplications.userId}).from(volunteerHours).innerJoin(volunteerApplications,and(eq(volunteerHours.applicationId,volunteerApplications.id),eq(volunteerApplications.ngoId,ngo.id))).where(eq(volunteerHours.id,data.hoursId));if(!record)throw new Error('Hours record not found.');await db.update(volunteerHours).set({status:data.status,reviewedBy:session.user.id,reviewedAt:new Date(),updatedAt:new Date()}).where(eq(volunteerHours.id,record.id));if(data.status==='approved'){const[sum]=await db.select({minutes:sql<number>`sum(${volunteerHours.minutes})::int`}).from(volunteerHours).innerJoin(volunteerApplications,eq(volunteerHours.applicationId,volunteerApplications.id)).where(and(eq(volunteerApplications.userId,record.userId),eq(volunteerApplications.ngoId,ngo.id),eq(volunteerHours.status,'approved')));await db.insert(volunteerCertificates).values({userId:record.userId,ngoId:ngo.id,certificateNumber:`DSV-${ngo.id.slice(0,4).toUpperCase()}-${record.userId.slice(0,8).toUpperCase()}`,approvedMinutes:sum.minutes}).onConflictDoUpdate({target:volunteerCertificates.certificateNumber,set:{approvedMinutes:sum.minutes,issuedAt:new Date()}})}revalidatePath('/ngo/dashboard/volunteers')}
