import { desc, eq } from 'drizzle-orm'
import { requireSession } from '@/lib/auth/session'
import { db } from '@/lib/db'
import { ngoProfiles, users, volunteerApplications, volunteerHours, volunteerOpportunities } from '@/lib/db/schema'
import { approveHoursAction, createOpportunityAction, decideApplicationAction } from './actions'

export default async function NgoVolunteersPage(){
  const session=await requireSession();const[ngo]=await db.select().from(ngoProfiles).where(eq(ngoProfiles.ownerId,session.user.id));if(!ngo)return <main className="p-10">Complete your NGO profile first.</main>
  const ops=await db.select().from(volunteerOpportunities).where(eq(volunteerOpportunities.ngoId,ngo.id)).orderBy(desc(volunteerOpportunities.createdAt))
  const applications=await db.select({id:volunteerApplications.id,status:volunteerApplications.status,message:volunteerApplications.message,user:users.name,opportunity:volunteerOpportunities.title}).from(volunteerApplications).innerJoin(users,eq(volunteerApplications.userId,users.id)).leftJoin(volunteerOpportunities,eq(volunteerApplications.opportunityId,volunteerOpportunities.id)).where(eq(volunteerApplications.ngoId,ngo.id))
  const hours=await db.select({id:volunteerHours.id,minutes:volunteerHours.minutes,serviceDate:volunteerHours.serviceDate,description:volunteerHours.description,status:volunteerHours.status,user:users.name}).from(volunteerHours).innerJoin(volunteerApplications,eq(volunteerHours.applicationId,volunteerApplications.id)).innerJoin(users,eq(volunteerApplications.userId,users.id)).where(eq(volunteerApplications.ngoId,ngo.id))
  return <main className="min-h-screen bg-slate-50"><div className="mx-auto max-w-6xl px-4 py-10"><h1 className="text-3xl font-bold">Volunteer operations</h1>
    <form action={createOpportunityAction} className="mt-6 grid gap-3 rounded-2xl border bg-white p-6 md:grid-cols-2"><h2 className="text-xl font-bold md:col-span-2">Publish opportunity</h2>{[['title','Title'],['city','City'],['state','State'],['capacity','Capacity'],['skills','Required skills, comma separated'],['availability','Availability']].map(([name,label])=><label key={name} className="text-sm font-semibold">{label}<input name={name} required className="mt-1 w-full rounded-lg border px-3 py-2"/></label>)}<textarea name="description" required minLength={40} placeholder="Description" className="rounded-lg border p-3 md:col-span-2"/><label className="text-sm"><input name="remote" type="checkbox"/> Remote allowed</label><button className="rounded-lg bg-blue-600 px-4 py-2 font-bold text-white">Publish</button></form>
    <h2 className="mt-10 text-xl font-bold">Published opportunities ({ops.length})</h2><div className="mt-3 grid gap-3 md:grid-cols-2">{ops.map(o=><div key={o.id} className="rounded-xl border bg-white p-4"><strong>{o.title}</strong><p className="text-sm text-slate-500">{o.status} · capacity {o.capacity}</p></div>)}</div>
    <h2 className="mt-10 text-xl font-bold">Applications</h2><div className="mt-3 space-y-3">{applications.map(a=><div key={a.id} className="rounded-xl border bg-white p-5"><strong>{a.user}</strong><p className="text-sm text-slate-600">{a.opportunity} · {a.status}</p><p className="mt-2 text-sm">{a.message}</p><form action={decideApplicationAction} className="mt-3 flex gap-2"><input type="hidden" name="applicationId" value={a.id}/>{['shortlisted','accepted','rejected'].map(s=><button key={s} name="status" value={s} className="rounded border px-3 py-1 text-sm">{s}</button>)}</form></div>)}</div>
    <h2 className="mt-10 text-xl font-bold">Service hours</h2><div className="mt-3 space-y-3">{hours.map(h=><div key={h.id} className="rounded-xl border bg-white p-5"><strong>{h.user} · {(h.minutes/60).toFixed(2)} hours</strong><p className="text-sm text-slate-500">{h.serviceDate} · {h.status}</p><p className="mt-2 text-sm">{h.description}</p>{h.status==='pending'&&<form action={approveHoursAction} className="mt-3 flex gap-2"><input type="hidden" name="hoursId" value={h.id}/><button name="status" value="approved" className="rounded bg-emerald-700 px-3 py-1 text-white">Approve</button><button name="status" value="rejected" className="rounded border px-3 py-1">Reject</button></form>}</div>)}</div>
  </div></main>
}
