import Link from 'next/link'
import { desc, eq } from 'drizzle-orm'
import { requireSession } from '@/lib/auth/session'
import { db } from '@/lib/db'
import { campaigns, donations, receipts, refunds, subscriptions } from '@/lib/db/schema'
import { formatPaise } from '@/lib/domain/finance'
import { requestRefundAction } from './actions'
export const dynamic='force-dynamic'
export default async function GivingPage(){const session=await requireSession();const gifts=await db.select({id:donations.id,amount:donations.amountPaise,status:donations.status,capturedAt:donations.capturedAt,campaign:campaigns.title,receiptId:receipts.id,refundStatus:refunds.status}).from(donations).innerJoin(campaigns,eq(donations.campaignId,campaigns.id)).leftJoin(receipts,eq(receipts.donationId,donations.id)).leftJoin(refunds,eq(refunds.donationId,donations.id)).where(eq(donations.donorId,session.user.id)).orderBy(desc(donations.capturedAt));const recurring=await db.select({id:subscriptions.id,amount:subscriptions.amountPaise,cadence:subscriptions.cadence,status:subscriptions.status,campaign:campaigns.title}).from(subscriptions).innerJoin(campaigns,eq(subscriptions.campaignId,campaigns.id)).where(eq(subscriptions.userId,session.user.id));return <main className="min-h-screen bg-slate-50"><div className="mx-auto max-w-5xl px-4 py-10"><h1 className="text-3xl font-bold">Giving and receipts</h1><h2 className="mt-8 text-xl font-bold">Captured donations</h2><div className="mt-4 space-y-4">{gifts.length?gifts.map(g=><article key={g.id} className="rounded-2xl border bg-white p-5"><div className="flex flex-wrap justify-between gap-3"><div><h3 className="font-bold">{g.campaign}</h3><p className="text-sm text-slate-500">{g.capturedAt.toLocaleDateString('en-IN')} · {g.status}</p></div><strong>{formatPaise(g.amount)}</strong></div><div className="mt-4 flex flex-wrap gap-3">{g.receiptId&&<Link href={`/api/receipts/${g.receiptId}`} className="text-sm font-bold text-blue-700">View receipt</Link>}{!g.refundStatus&&<details><summary className="cursor-pointer text-sm font-bold text-amber-700">Request refund</summary><form action={requestRefundAction} className="mt-3 flex gap-2"><input type="hidden" name="donationId" value={g.id}/><input name="reason" required minLength={20} placeholder="Reason (minimum 20 characters)" className="rounded-lg border px-3 py-2"/><button className="rounded-lg bg-slate-900 px-3 py-2 text-sm text-white">Submit</button></form></details>}{g.refundStatus&&<span className="text-sm text-slate-600">Refund: {g.refundStatus}</span>}</div></article>):<p className="rounded-xl border bg-white p-6 text-slate-500">No captured donations yet.</p>}</div><h2 className="mt-10 text-xl font-bold">Recurring gifts</h2><div className="mt-4 space-y-3">{recurring.length?recurring.map(s=><div key={s.id} className="flex justify-between rounded-xl border bg-white p-5"><span>{s.campaign} · {s.cadence}</span><strong>{formatPaise(s.amount)} · {s.status}</strong></div>):<p className="rounded-xl border bg-white p-6 text-slate-500">No recurring gifts.</p>}</div></div></main>}
