'use server'
import { and, eq } from 'drizzle-orm'
import { revalidatePath } from 'next/cache'
import { z } from 'zod'
import { requireSession } from '@/lib/auth/session'
import { db } from '@/lib/db'
import { ngoProfiles, notifications, volunteerApplications, volunteerHours, volunteerOpportunities, volunteerProfiles } from '@/lib/db/schema'

const list=(value:FormDataEntryValue|null)=>String(value??'').split(',').map(x=>x.trim().toLowerCase()).filter(Boolean)
export async function saveVolunteerProfileAction(form:FormData){const session=await requireSession();const parsed=z.object({bio:z.string().trim().min(20).max(1500),city:z.string().trim().min(2).max(100),state:z.string().trim().min(2).max(100)}).parse(Object.fromEntries(form));await db.insert(volunteerProfiles).values({userId:session.user.id,...parsed,skills:list(form.get('skills')),availability:list(form.get('availability')),remoteOk:form.get('remoteOk')==='on'}).onConflictDoUpdate({target:volunteerProfiles.userId,set:{...parsed,skills:list(form.get('skills')),availability:list(form.get('availability')),remoteOk:form.get('remoteOk')==='on',updatedAt:new Date()}});revalidatePath('/volunteer/profile')}
export async function applyOpportunityAction(form:FormData){const session=await requireSession();if(!session.user.emailVerified)throw new Error('Verify your email before applying.');const id=z.string().uuid().parse(form.get('opportunityId'));const[op]=await db.select().from(volunteerOpportunities).where(and(eq(volunteerOpportunities.id,id),eq(volunteerOpportunities.status,'published'))).limit(1);if(!op)throw new Error('Opportunity is not available.');const[profile]=await db.select().from(volunteerProfiles).where(eq(volunteerProfiles.userId,session.user.id)).limit(1);if(!profile)throw new Error('Complete your volunteer profile first.');await db.insert(volunteerApplications).values({userId:session.user.id,ngoId:op.ngoId,opportunityId:op.id,message:String(form.get('message')??''),status:'submitted'}).onConflictDoNothing();const[ngo]=await db.select({ownerId:ngoProfiles.ownerId}).from(ngoProfiles).where(eq(ngoProfiles.id,op.ngoId));if(ngo)await db.insert(notifications).values({userId:ngo.ownerId,type:'volunteer_application',title:'New volunteer application',body:`A volunteer applied for ${op.title}.`,href:'/ngo/dashboard/volunteers'});revalidatePath('/volunteer/opportunities')}
export async function submitVolunteerHoursAction(form:FormData){const session=await requireSession();const data=z.object({applicationId:z.string().uuid(),hours:z.coerce.number().positive().max(24),serviceDate:z.string().date(),description:z.string().trim().min(10).max(1000)}).parse(Object.fromEntries(form));const[application]=await db.select().from(volunteerApplications).where(and(eq(volunteerApplications.id,data.applicationId),eq(volunteerApplications.userId,session.user.id),eq(volunteerApplications.status,'accepted'))).limit(1);if(!application)throw new Error('Only accepted volunteer service can be logged.');await db.insert(volunteerHours).values({applicationId:application.id,minutes:Math.round(data.hours*60),serviceDate:data.serviceDate,description:data.description});revalidatePath('/dashboard/volunteering')}
