'use server'
import { createHash, randomBytes } from 'node:crypto'
import { and, eq } from 'drizzle-orm'
import { redirect } from 'next/navigation'
import { revalidatePath } from 'next/cache'
import { z } from 'zod'
import { requireSession } from '@/lib/auth/session'
import { db } from '@/lib/db'
import { campaigns, corporateEmployees, corporateProfiles, csrInitiatives, ngoProfiles } from '@/lib/db/schema'
import { mailProvider } from '@/lib/providers/mail'
async function corporate(){const session=await requireSession();if(session.user.role!=='corporate')throw new Error('Corporate account required.');const[profile]=await db.select().from(corporateProfiles).where(eq(corporateProfiles.ownerId,session.user.id));return{session,profile}}
export async function saveCorporateProfileAction(form:FormData){const{session}=await corporate();const data=z.object({name:z.string().trim().min(2).max(160),cin:z.string().trim().regex(/^[A-Z0-9]{21}$/,'Enter a valid 21-character CIN.'),description:z.string().trim().max(3000),websiteUrl:z.string().url().optional().or(z.literal(''))}).parse(Object.fromEntries(form));await db.insert(corporateProfiles).values({ownerId:session.user.id,...data,websiteUrl:data.websiteUrl||null}).onConflictDoUpdate({target:corporateProfiles.ownerId,set:{...data,websiteUrl:data.websiteUrl||null,updatedAt:new Date()}});redirect('/corporate/dashboard')}
export async function inviteEmployeeAction(form:FormData){const{profile}=await corporate();if(!profile)throw new Error('Complete the corporate profile first.');const data=z.object({name:z.string().trim().min(2).max(120),email:z.string().email().transform(x=>x.toLowerCase()),title:z.string().trim().max(120)}).parse(Object.fromEntries(form));const token=randomBytes(32).toString('base64url');const hash=createHash('sha256').update(token).digest('hex');await db.insert(corporateEmployees).values({corporateId:profile.id,...data,inviteTokenHash:hash}).onConflictDoUpdate({target:[corporateEmployees.corporateId,corporateEmployees.email],set:{...data,inviteTokenHash:hash,status:'invited',invitedAt:new Date()}});await mailProvider.send({to:data.email,subject:`Join ${profile.name} on DaanSetu`,text:`Accept your employee invitation: ${process.env.APP_URL}/corporate/invitations/${token}`});revalidatePath('/corporate/employees')}
export async function createInitiativeAction(form:FormData){const{profile}=await corporate();if(!profile)throw new Error('Complete the corporate profile first.');const data=z.object({campaignId:z.string().uuid(),title:z.string().trim().min(8).max(160),description:z.string().trim().min(30).max(4000),matchPercentage:z.coerce.number().int().min(0).max(500),perEmployeeCapRupees:z.coerce.number().int().min(0),programCapRupees:z.coerce.number().int().min(1),startsAt:z.coerce.date(),endsAt:z.coerce.date()}).parse(Object.fromEntries(form));if(data.endsAt<=data.startsAt)throw new Error('End date must follow start date.');const[campaign]=await db.select({id:campaigns.id,verified:ngoProfiles.verificationStatus}).from(campaigns).innerJoin(ngoProfiles,eq(campaigns.ngoId,ngoProfiles.id)).where(and(eq(campaigns.id,data.campaignId),eq(campaigns.status,'active')));if(!campaign||campaign.verified!=='verified')throw new Error('CSR initiatives require an active campaign from a verified NGO.');await db.insert(csrInitiatives).values({corporateId:profile.id,campaignId:data.campaignId,title:data.title,description:data.description,matchPercentage:data.matchPercentage,perEmployeeCapPaise:data.perEmployeeCapRupees*100,programCapPaise:data.programCapRupees*100,startsAt:data.startsAt,endsAt:data.endsAt,status:'active'});redirect('/corporate/campaigns')}
