import Link from 'next/link'
import { searchCampaigns } from '@/lib/repositories/discovery'
import { formatPaise } from '@/lib/domain/finance'

export const dynamic = 'force-dynamic'
const categories = ['education', 'food', 'health', 'women', 'animals', 'disaster', 'environment']

export default async function CampaignsPage({ searchParams }: { searchParams: Promise<{ search?: string; category?: string; sort?: string; page?: string }> }) {
  const params = await searchParams
  const campaigns = await searchCampaigns({ ...params, page: Number(params.page) || 1 })
  return <main className="min-h-screen bg-slate-50"><div className="mx-auto max-w-7xl px-4 py-10">
    <div className="flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-4xl font-bold text-slate-950">Active campaigns</h1><p className="mt-2 text-slate-600">Every campaign shown here is approved and connected to an active payout account.</p></div><Link href="/campaigns/create" className="rounded-xl bg-blue-600 px-5 py-3 font-semibold text-white">Start a fundraiser</Link></div>
    <form className="mt-8 grid gap-3 rounded-2xl border bg-white p-5 md:grid-cols-[1fr_220px_180px_auto]"><input name="search" defaultValue={params.search} aria-label="Search campaigns" placeholder="Search campaigns" className="rounded-xl border px-4 py-3"/><select name="category" defaultValue={params.category ?? ''} className="rounded-xl border px-4 py-3"><option value="">All causes</option>{categories.map(c => <option key={c}>{c}</option>)}</select><select name="sort" defaultValue={params.sort ?? 'new'} className="rounded-xl border px-4 py-3"><option value="new">Newest</option><option value="deadline">Ending soon</option><option value="funded">Most funded</option></select><button className="rounded-xl bg-slate-900 px-5 py-3 font-semibold text-white">Apply</button></form>
    {campaigns.length === 0 ? <div className="mt-8 rounded-2xl border bg-white p-12 text-center"><h2 className="text-xl font-bold">No matching active campaigns</h2><p className="mt-2 text-slate-600">Try a broader cause or search term.</p></div> : <div className="mt-8 grid gap-6 md:grid-cols-2 lg:grid-cols-3">{campaigns.map(c => { const progress = Math.min(100, c.raisedPaise / c.targetPaise * 100); return <Link key={c.id} href={`/campaigns/${c.id}`} className="overflow-hidden rounded-2xl border bg-white shadow-sm transition hover:-translate-y-1 hover:shadow-lg"><div className="flex h-44 items-center justify-center bg-gradient-to-br from-blue-100 to-emerald-50 text-5xl">{c.imageUrl ? <img src={c.imageUrl} alt="" className="h-full w-full object-cover"/> : '🤝'}</div><div className="p-5"><span className="text-xs font-bold uppercase tracking-wide text-blue-700">{c.category}</span><h2 className="mt-2 text-xl font-bold text-slate-950">{c.title}</h2><p className="mt-2 line-clamp-2 text-sm text-slate-600">{c.summary ?? c.story}</p><p className="mt-3 text-sm font-medium text-blue-700">by {c.ngoName ?? 'Verified beneficiary'}</p><div className="mt-5 h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full bg-emerald-500" style={{width: `${progress}%`}}/></div><div className="mt-2 flex justify-between text-sm"><strong>{formatPaise(c.raisedPaise)}</strong><span className="text-slate-500">of {formatPaise(c.targetPaise)}</span></div></div></Link>})}</div>}
  </div></main>
}
