'use client'
import Link from 'next/link'
import { motion } from 'framer-motion'
import { ArrowRight, BadgeCheck, HandCoins, MapPin, ReceiptText } from 'lucide-react'
import { formatPaise } from '@/lib/domain/finance'

export default function ImpactDashboard({ data }: { data: { fundsPaise: number; donationCount: number; activeCampaigns: number; verifiedNgos: number; statesReached: number } }) {
  const stats = [{ label: 'Captured donations', value: formatPaise(data.fundsPaise), icon: HandCoins, color: 'text-blue-600' }, { label: 'Transactions', value: data.donationCount.toLocaleString('en-IN'), icon: ReceiptText, color: 'text-emerald-600' }, { label: 'Active campaigns', value: data.activeCampaigns.toLocaleString('en-IN'), icon: BadgeCheck, color: 'text-purple-600' }, { label: 'Verified NGOs', value: data.verifiedNgos.toLocaleString('en-IN'), icon: BadgeCheck, color: 'text-amber-600' }, { label: 'States reached', value: data.statesReached.toLocaleString('en-IN'), icon: MapPin, color: 'text-teal-600' }]
  return <section className="section bg-white pb-16 pt-10"><div className="container-custom"><div className="relative overflow-hidden rounded-[32px] border border-slate-200/70 bg-[#f8fafc] p-8 md:p-12"><div className="grid items-center gap-12 lg:grid-cols-12"><motion.div initial={{opacity:0,x:-20}} whileInView={{opacity:1,x:0}} viewport={{once:true}} className="z-10 lg:col-span-3"><h2 className="mb-5 font-serif text-3xl font-bold leading-tight text-[#1e3a8a]">Track. Measure.<br/>Multiply Impact.</h2><p className="mb-8 text-[15px] leading-relaxed text-slate-600">These totals come only from captured payments and approved platform records.</p><Link href="/analytics" className="flex w-fit items-center gap-2 rounded-lg border border-blue-200 bg-white px-6 py-2.5 text-[13px] font-bold text-blue-600">View Full Dashboard <ArrowRight className="h-4 w-4"/></Link></motion.div><motion.div initial={{opacity:0,x:20}} whileInView={{opacity:1,x:0}} viewport={{once:true}} className="z-10 rounded-[24px] border border-slate-200/80 bg-white p-6 shadow-[0_8px_30px_rgb(0,0,0,0.06)] lg:col-span-9"><h3 className="mb-6 text-[15px] font-bold text-[#1e3a8a]">DaanSetu Public Impact</h3><div className="grid grid-cols-2 gap-3 md:grid-cols-5">{stats.map(s => <div key={s.label} className="rounded-xl border border-slate-100 bg-white p-4 shadow-sm"><s.icon className={`mb-3 h-6 w-6 ${s.color}`}/><p className={`truncate text-sm font-bold ${s.color}`}>{s.value}</p><p className="mt-1 text-[10px] font-semibold text-slate-500">{s.label}</p></div>)}</div><div className="mt-6 rounded-xl border border-slate-100 p-5"><h4 className="text-sm font-bold text-slate-800">How totals are counted</h4><p className="mt-2 text-sm leading-6 text-slate-600">Gateway-created orders are excluded. Funds appear only after verified capture; refunds and reversals remain separately auditable.</p></div></motion.div></div></div></div></section>
}
